spring:
  application:
    name: e-learning
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://localhost:5432/db_eleaning_a001
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1929
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://127.0.0.1:8080/realms/master
server:
  port: 8090
